In [4]:
import numpy as np

## array

In [6]:
np.array([1,2,3])

array([1, 2, 3])

In [10]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2=np.arange(5,11)
arr2

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr3=np.arange(5,11,2)
arr3

array([5, 7, 9])

In [15]:
arr4=np.arange(5, 11, 2.0)
arr4

array([5., 7., 9.])

## linspace

In [17]:
arr1=np.linspace(1,10,5)
arr1

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [18]:
arr3=np.linspace(0,np.pi,20)
arr3

array([0.        , 0.16534698, 0.33069396, 0.49604095, 0.66138793,
       0.82673491, 0.99208189, 1.15742887, 1.32277585, 1.48812284,
       1.65346982, 1.8188168 , 1.98416378, 2.14951076, 2.31485774,
       2.48020473, 2.64555171, 2.81089869, 2.97624567, 3.14159265])

## reshape

In [21]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
arr2=arr1.reshape(2,5)
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [25]:
arr3=arr2.reshape(-1)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
arr1.reshape(-1, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [28]:
arr1.shape

(10,)

# pandas

In [31]:

import pandas as pd

In [33]:
s1=pd.Series([1,3,5,np.nan,6,8])
s1

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64